// ENUM WORKS IN TYPESCRIPT FOR FIXED STRINGS
enum CATEGORY_ACTION_TYPES {
  FETCH_CURRENT_CATEGORY_START = "category/SET_CURRENT_CATEGORY_START",
  FETCH_CURRENT_CATEGORY_SUCCESS = "category/SET_CURRENT_CATEGORY_SUCCESS",
  FETCH_CURRENT_CATEGORY_FAILED = "category/SET_CURRENT_CATEGORY_FAIL",
}

// const CATEGORY_ACTION_TYPES = {
//   FETCH_CURRENT_CATEGORY_START: "category/SET_CURRENT_CATEGORY_START",
//   FETCH_CURRENT_CATEGORY_SUCCESS: "category/SET_CURRENT_CATEGORY_SUCCESS",
//   FETCH_CURRENT_CATEGORY_FAILED: "category/SET_CURRENT_CATEGORY_FAIL",
// };

export default CATEGORY_ACTION_TYPES;
